name: Python Flake8, black, pylint and superlinter code quality check

on: [push]

jobs:
  lint:
    uses: mundialis/github-workflows/.github/workflows/linting.yml@main
    with:
      VALIDATE_JAVASCRIPT_STANDARD: false
      BASH_SEVERITY: 'warning'